matrix:
  include:
    - os: linux
      sudo: required
      language: c
      language: cpp
      language: node_js
      language: python
      compiler: clang
      node_js: 4.2.3
      python: 2.7
      dist: trusty
    - os: osx
      sudo: required
      language: c
      language: cpp
      language: node_js
      compiler: clang
      node_js: 4.2.3
      osx_image: xcode7.3
      # language: python  # does not work on travis osx, so we install with brew...

branches:
  only:
    - travis
cache:
  directories:
    - node_modules
    - $HOME/.electron
    - $HOME/.cache/fpm

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gnu-tar dpkg libicns graphicsmagick lzip python; fi
install:
  - npm install npm -g
  - npm install
  - npm prune
  - pip install -q --upgrade setuptools pip
  - pip install -q jupyter
  - pip install -q numpy matplotlib plotly toyplot ipywidgets==4.1.1 pandas
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - npm run test
